/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account;
import model.AccountDirectory;


/**
 *
 * @author linyuxiao
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    private Account account;
    
    public ViewAccountJPanel(JPanel userProcessContainer, AccountDirectory directory, Account account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAge = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        HomeJPanel = new javax.swing.JPanel();
        lblStreetAdressHome = new javax.swing.JLabel();
        lblUnitNumberHome = new javax.swing.JLabel();
        txtStreetAddressHome = new javax.swing.JTextField();
        txtUnitNumberHome = new javax.swing.JTextField();
        lblCityHome = new javax.swing.JLabel();
        lblStateHome = new javax.swing.JLabel();
        txtCityHome = new javax.swing.JTextField();
        txtStateHome = new javax.swing.JTextField();
        lblZipCodeHome = new javax.swing.JLabel();
        lblPhoneNumberHome = new javax.swing.JLabel();
        txtZipCodeHome = new javax.swing.JTextField();
        txtPhoneNumberHome = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        WorkJPanel = new javax.swing.JPanel();
        lblStreetAddressWork = new javax.swing.JLabel();
        lblUnitNumberWork = new javax.swing.JLabel();
        txtStreetAddressWork = new javax.swing.JTextField();
        txtUnitNumberWork = new javax.swing.JTextField();
        lblCityWork = new javax.swing.JLabel();
        lblStateWork = new javax.swing.JLabel();
        txtCityWork = new javax.swing.JTextField();
        txtStateWork = new javax.swing.JTextField();
        lblZipCodeWork = new javax.swing.JLabel();
        lblPhoneNumberWork = new javax.swing.JLabel();
        txtZipCodeWork = new javax.swing.JTextField();
        txtPhoneNumberWork = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblCreate.setBackground(new java.awt.Color(255, 255, 255));
        lblCreate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("View Account");

        lblFirstName.setText("First Name");

        HomeJPanel.setBackground(new java.awt.Color(0, 255, 204));
        HomeJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblStreetAdressHome.setText("Street Address");

        lblUnitNumberHome.setText("Unit Number");

        lblCityHome.setText("City");

        lblStateHome.setText("State");

        txtStateHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHomeActionPerformed(evt);
            }
        });

        lblZipCodeHome.setText("Zip Code");

        lblPhoneNumberHome.setText("Phone Number");

        javax.swing.GroupLayout HomeJPanelLayout = new javax.swing.GroupLayout(HomeJPanel);
        HomeJPanel.setLayout(HomeJPanelLayout);
        HomeJPanelLayout.setHorizontalGroup(
            HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStreetAdressHome)
                    .addComponent(txtStreetAddressHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityHome)
                    .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCodeHome)
                    .addComponent(txtZipCodeHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnitNumberHome)
                    .addComponent(txtUnitNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateHome)
                    .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumberHome)
                    .addComponent(txtPhoneNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        HomeJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCityHome, lblPhoneNumberHome, lblStateHome, lblStreetAdressHome, lblUnitNumberHome, lblZipCodeHome, txtCityHome, txtPhoneNumberHome, txtStateHome, txtStreetAddressHome, txtUnitNumberHome, txtZipCodeHome});

        HomeJPanelLayout.setVerticalGroup(
            HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAdressHome)
                    .addComponent(lblUnitNumberHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddressHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityHome)
                    .addComponent(lblStateHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCodeHome)
                    .addComponent(lblPhoneNumberHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCodeHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblLastName.setText("Last Name");

        lblHomeAddress.setFont(new java.awt.Font("Didot", 2, 14)); // NOI18N
        lblHomeAddress.setText("Home Address");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        WorkJPanel.setBackground(new java.awt.Color(0, 255, 204));
        WorkJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblStreetAddressWork.setText("Street Address");

        lblUnitNumberWork.setText("Unit Number");

        lblCityWork.setText("City");

        lblStateWork.setText("State");

        txtStateWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateWorkActionPerformed(evt);
            }
        });

        lblZipCodeWork.setText("Zip Code");

        lblPhoneNumberWork.setText("Phone Number");

        javax.swing.GroupLayout WorkJPanelLayout = new javax.swing.GroupLayout(WorkJPanel);
        WorkJPanel.setLayout(WorkJPanelLayout);
        WorkJPanelLayout.setHorizontalGroup(
            WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStreetAddressWork)
                    .addComponent(txtStreetAddressWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityWork)
                    .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCodeWork)
                    .addComponent(txtZipCodeWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnitNumberWork)
                    .addComponent(txtUnitNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateWork)
                    .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumberWork)
                    .addComponent(txtPhoneNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        WorkJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCityWork, lblPhoneNumberWork, lblStateWork, lblStreetAddressWork, lblUnitNumberWork, lblZipCodeWork, txtCityWork, txtPhoneNumberWork, txtStateWork, txtStreetAddressWork, txtUnitNumberWork, txtZipCodeWork});

        WorkJPanelLayout.setVerticalGroup(
            WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddressWork)
                    .addComponent(lblUnitNumberWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddressWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityWork)
                    .addComponent(lblStateWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCodeWork)
                    .addComponent(lblPhoneNumberWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCodeWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblSSN.setText("Social Security Number");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblWorkAddress.setFont(new java.awt.Font("Didot", 2, 14)); // NOI18N
        lblWorkAddress.setText("Work Address");

        lblAge.setText("Age");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAge))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkAddress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblFirstName, lblLastName, lblSSN, txtAge, txtFirstName, txtLastName, txtSSN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHomeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWorkAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStateHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHomeActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtStateWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateWorkActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String SSN = txtSSN.getText();
        String streetAddressHome = txtStreetAddressHome.getText();
        String unitNumberHome = txtUnitNumberHome.getText();
        String cityHome = txtCityHome.getText();
        String stateHome = txtStateHome.getText();
        String zipCodeHome = txtZipCodeHome.getText();
        String phoneNumberHome = txtPhoneNumberHome.getText();
        String streetAddressWork = txtStreetAddressWork.getText();
        String unitNumberWork = txtUnitNumberWork.getText();
        String cityWork = txtCityWork.getText();
        String stateWork = txtStateWork.getText();
        String zipCodeWork = txtZipCodeWork.getText();
        String phoneNumberWork = txtPhoneNumberWork.getText();
        
//      boolean isFirstNameBlank = firstName.isBlank();
        
        if (firstName.isBlank() || lastName.isBlank() || streetAddressHome.isBlank() || unitNumberHome.isBlank() || cityHome.isBlank() || stateHome.isBlank() || zipCodeHome.isBlank() || phoneNumberHome.isBlank() || streetAddressWork.isBlank() || unitNumberWork.isBlank() || cityWork.isBlank() || stateWork.isBlank() || zipCodeWork.isBlank() || phoneNumberWork.isBlank())
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            //pause until the user closes the dialog.
            return;
        }
        
        try {
            int age = Integer.parseInt(txtAge.getText()); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for age.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for (int i = 0; i < SSN.length(); i++) {
            if (SSN.length() != 9 || !Character.isDigit(SSN.charAt(i))){
                JOptionPane.showMessageDialog(this, "Please enter valid numeric values for SSN.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        try {
            int zipCodeHomeNumber = Integer.parseInt(zipCodeHome); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Zip Code (Home).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            int zipCodeWorkNumber = Integer.parseInt(zipCodeWork); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Zip Code (Work).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            long phoneNumberH = Long.parseLong(phoneNumberHome); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Phone Number (Home).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            long phoneNumberW = Long.parseLong(phoneNumberWork); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Phone Number (Work).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        if (txtSSN.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "Please enter a valid 9-digit SSN", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (zipCodeHome.length() != 5 || zipCodeWork.length() != 5) {
            JOptionPane.showMessageDialog(this, "Please enter a valid 5-digit Zip Code", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (phoneNumberHome.length() != 10 || phoneNumberWork.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please enter a valid 10-digit Phone Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        account.setFirstName(firstName);
        account.setLastName(lastName);
        int age = Integer.parseInt(txtAge.getText());
        
        account.setSocialSecurityNumber(SSN);
        account.setAge(age);
        
        account.setHomeAddress(streetAddressHome, unitNumberHome, cityHome, stateHome, zipCodeHome, phoneNumberHome);

        account.setWorkAddress(streetAddressWork, unitNumberWork, cityWork, stateWork, zipCodeWork, phoneNumberWork);

        
        
        JOptionPane.showMessageDialog(null, "Account successfully updated.", "Warning", JOptionPane.WARNING_MESSAGE);
        
        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeJPanel;
    private javax.swing.JPanel WorkJPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityHome;
    private javax.swing.JLabel lblCityWork;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumberHome;
    private javax.swing.JLabel lblPhoneNumberWork;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblStateHome;
    private javax.swing.JLabel lblStateWork;
    private javax.swing.JLabel lblStreetAddressWork;
    private javax.swing.JLabel lblStreetAdressHome;
    private javax.swing.JLabel lblUnitNumberHome;
    private javax.swing.JLabel lblUnitNumberWork;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCodeHome;
    private javax.swing.JLabel lblZipCodeWork;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityHome;
    private javax.swing.JTextField txtCityWork;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumberHome;
    private javax.swing.JTextField txtPhoneNumberWork;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStateHome;
    private javax.swing.JTextField txtStateWork;
    private javax.swing.JTextField txtStreetAddressHome;
    private javax.swing.JTextField txtStreetAddressWork;
    private javax.swing.JTextField txtUnitNumberHome;
    private javax.swing.JTextField txtUnitNumberWork;
    private javax.swing.JTextField txtZipCodeHome;
    private javax.swing.JTextField txtZipCodeWork;
    // End of variables declaration//GEN-END:variables
    
     

    
    private void refreshTextFields() {
        txtFirstName.setText(account.getFirstName());
        txtLastName.setText(account.getLastName());
        txtSSN.setText(String.valueOf(account.getSocialSecurityNumber()));
        txtAge.setText(String.valueOf(account.getAge()));
        
        String[] homeAddress = account.getHomeAddressDetails();
        txtStreetAddressHome.setText(homeAddress[0]);
        txtUnitNumberHome.setText(homeAddress[1]);
        txtCityHome.setText(homeAddress[2]);
        txtStateHome.setText(homeAddress[3]);
        txtZipCodeHome.setText(homeAddress[4]);
        txtPhoneNumberHome.setText(homeAddress[5]);
        
        String[] workAddress = account.getWorkAddressDetails();
        txtStreetAddressWork.setText(workAddress[0]);
        txtUnitNumberWork.setText(workAddress[1]);
        txtCityWork.setText(workAddress[2]);
        txtStateWork.setText(workAddress[3]);
        txtZipCodeWork.setText(workAddress[4]);
        txtPhoneNumberWork.setText(workAddress[5]);
        
    }
    
    private void setViewMode() {
        
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtSSN.setEnabled(false);
        txtAge.setEnabled(false);
        txtStreetAddressHome.setEnabled(false);
        txtUnitNumberHome.setEnabled(false);
        txtCityHome.setEnabled(false);
        txtStateHome.setEnabled(false);
        txtZipCodeHome.setEnabled(false);
        txtPhoneNumberHome.setEnabled(false);
        txtStreetAddressWork.setEnabled(false);
        txtUnitNumberWork.setEnabled(false);
        txtCityWork.setEnabled(false);
        txtStateWork.setEnabled(false);
        txtZipCodeWork.setEnabled(false);
        txtPhoneNumberWork.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
                
    }
    
    private void setEditMode() {
        
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSN.setEnabled(true);
        txtAge.setEnabled(true);
        txtStreetAddressHome.setEnabled(true);
        txtUnitNumberHome.setEnabled(true);
        txtCityHome.setEnabled(true);
        txtStateHome.setEnabled(true);
        txtZipCodeHome.setEnabled(true);
        txtPhoneNumberHome.setEnabled(true);
        txtStreetAddressWork.setEnabled(true);
        txtUnitNumberWork.setEnabled(true);
        txtCityWork.setEnabled(true);
        txtStateWork.setEnabled(true);
        txtZipCodeWork.setEnabled(true);
        txtPhoneNumberWork.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
}
